# This is a basic workflow to help you get started with Actions

name: Unity CI Builds 👷🏽‍♂️

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2.3.3
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2.1.2
        with:
          path: Cache
          key: Cache

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.7
        with:
          unityVersion: 2019.4.13f1

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v2.0-alpha-1
        with:
          unityVersion: 2019.4.13f1
          targetPlatform: WebGL

      # Output
      - uses: actions/upload-artifact@v2.2.0
        with:
          name: Build
          path: build
